title: xpwnd4
description: Cybersecurity writeups, labs, projects, and research
baseurl: ""
url: ""
theme: jekyll-theme-hacker
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  writeups:
    output: true
    permalink: /writeups/:name/
  projects:
    output: true
    permalink: /projects/:name/
  resources:
    output: true
    permalink: /resources/:name/
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: writeups
    values:
      layout: writeup
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: resources
    values:
      layout: resource
